version: '2'

networks:
  distributed-locks:
    driver: bridge

services:
  redis:
    container_name: distributed-locks-redis
    image: 'bitnami/redis:latest'
    ports : 
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - distributed-locks